config/routes.rb
Userpub::Application.routes.draw do
  get '/logout', to: 'sessions#destroy'
  constraints host: /^(#{ENV['APP_HOST']}|userpub.r13.railsrumble.com)$/i do
    get '/', to: redirect("http://www.#{ENV['APP_HOST']}/")
    get '*path', to: redirect("http://www.#{ENV['APP_HOST']}/%{path}")
  end

  constraints host: 'userpub.r12.railsrumble.com' do
    get '*path', to: redirect("http://www.#{ENV['APP_HOST']}/%{path}")
  end
  
  constraints LanderConstraint.new do
    root to: 'lander#show', id: 'home'
    post '/demo', to: 'sessions#demo'
    post '/auth/persona/callback', to: 'sessions#account'
    resources :accounts do
      member do
        get :token, to: "accounts#new_token"
        post :token, to: "accounts#create_token"
      end
    end
    get '/:id', to: 'lander#show'
  end
  
  constraints AccountConstraint.new do
    get '/auth/jwt/callback', to: 'sessions#create'
    root to: 'accounts#show', as: 'account_root'
  end
end

app/models/account.rb
class Account
  include MongoMapper::Document

  key :name, String, required: true
  key :subdomain, String, required: true
  key :host, String
  key :email, String, required: true
  key :support_email, String
  key :staff_domain, String
  key :login_url, String
  token :secret, size: 20
  timestamps!
  
  validates_uniqueness_of :subdomain, :host, allow_blank: true
  validates_format_of :subdomain, with: /\A[a-z][a-z0-9]+$\z/
  validates_format_of :host, with: /\A(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$\z/, allow_blank: true
  
  many :users
  
  def self.find_by_env(env)
    return find_by_subdomain(ENV['DEBUG_SUBDOMAIN']) if ENV['DEBUG_SUBDOMAIN'] && ENV['RACK_ENV'] == 'development'
      
    request = Rack::Request.new(env)
    
    host = request.host
    Rails.logger.debug "Account: looking up account for #{request.host}"
    subdomain = host.split('.').first if host.include?(ENV['APP_HOST'])
    Account.find_by_subdomain(subdomain) || Account.find_by_host(request.host)
  end
  
  def make_token(claims)
    JWT.encode(claims, secret)
  end
  
  def staff_email?(email)
    email.split("@").last == staff_domain
  end
  
  def preferred_host
    host?? host : "#{subdomain}.#{ENV['APP_HOST']}"
  end
end

app/models/account_constraint.rb
class AccountConstraint
  def initialize(inverse = false)
    @inverse = inverse
  end
  
  def matches?(request)
    match = !!Account.find_by_env(request.env)
    match = !match if @inverse
    match
  end
end

app/models/lander_constraint.rb
class LanderConstraint
  def initialize(on = true)
    @on = on
  end
  
  def matches?(request)
    lander = (ENV['DEBUG_SUBDOMAIN'] || request.subdomain) == 'www'
    @on ? lander : !lander
  end
end

app/models/user.rb
class User
  include MongoMapper::Document

  key :uid, String, required: true
  key :name, String, required: true
  key :email, String, required: true
  key :admin, Boolean, default: false
  key :staff, Boolean, default: false
  key :title, String
  key :pic, String
  
  timestamps!
  
  belongs_to :account
  
  validates_uniqueness_of :email, :uid, scope: :account_id
  
  def self.from_jwt(jwt, account)
    user = account.users.find_by_uid(jwt.id)
    user ||= User.new(uid: jwt.id, account: account)
    
    user.name = jwt.name
    user.email = jwt.email
    user.pic = jwt.pic
    user.title = jwt.title
    user.admin = jwt.admin
    user.staff = jwt.staff
    
    user.staff = true if !jwt.key?(:staff) && account.staff_email?(jwt.email)
    
    user.save!
    
    user
  end
  
  def avatar
    pic || Gravatar.new(email).image_url
  end
  
  def firebase_token
    JWT.encode({iat: Time.now.to_i, v: 0, d: as_json}, ENV['FIREBASE_SECRET'])
  end
  
  def jwt_token
    JWT.encode({id: id.to_s, name: name, email: email, staff: staff, admin: admin, title: title, pic: pic}, account.secret)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  respond_to :html
  
  before_filter :persona_required, only: [:index, :create, :destroy, :edit, :update]
  before_filter :find_account, only: [:update, :destroy, :edit, :new_token, :create_token]
  layout 'manage', except: [:show]
  
  def show
    redirect_to accounts_path unless current_account
  end
  
  def index
    @accounts = Account.where(email: persona)
    respond_with @accounts
  end
  
  def create
    @account = Account.new({email: persona}.merge(params[:account]))
    flash[:notice] = "Successfully created account!" if @account.save
    respond_with @account
  end
  
  def new_token
    render action: :token
  end
  
  def create_token
    @payload = JWT.encode(params[:token].reject{|k,v| v.blank?}, @account.secret)
    render action: :token
  end

  def destroy
    @account.destroy
    redirect_to accounts_path
  end
  
  def edit
  end
  
  def new
    @account = Account.new(params[:account])
  end
  
  def update
    flash[:notice] = "Updated account successfully." if @account.update_attributes(params[:account])
    respond_with @account
  end
  
  def missing
    render text: 'Not Found', status: 404
  end
  
  protected
  
  def find_account
    @account = Account.where(email: persona).find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  
  protected
  
  def current_account
    @current_account ||= Account.find_by_env(request.env)
  end
  
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
  
  def account_required
    render text: "Not Found", status: 404 unless current_account
  end
  
  def staff_required
    render text: "Must be staff to do that.", status: 401 unless current_user.try(:staff?)
  end
  
  def persona_required
    redirect_to "/", alert: "Must be logged in to see that." unless persona
  end
  
  def persona
    session[:persona]
  end
  
  helper_method :current_account, :current_user, :logged_in?, :persona
end

app/controllers/lander_controller.rb
class LanderController < ApplicationController
  def show
    render template: "lander/#{params[:id]}"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_jwt(auth_hash.extra.raw_info, current_account)
    reset_session
    session[:user_id] = user.id.to_s
    redirect_to session['omniauth.origin'] || '/'
  end
  
  def demo
    account = Account.find_by_subdomain('demo')
    payload = JWT.encode({
      id: params[:name].gsub(" ","").underscore,
      name: params[:name],
      email: "demo#{SecureRandom.hex(10)}@example.com",
      staff: false,
      admin: false
    }, account.secret)
    redirect_to "http://demo.#{ENV['APP_HOST']}/auth/jwt/callback?jwt=#{payload}"
  end

  def account
    session[:persona] = auth_hash.uid
    redirect_to accounts_path
  end

  def destroy
    reset_session
    redirect_to '/'
  end
  
  protected
  
  def auth_hash
    request.env['omniauth.auth']
  end
end

app/views/accounts/_form.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><% if account.new_record? %>Create a New Account<% else %>Update <%= account.name %><% end %></div>
  <div class="panel-body">
    <%= form_for account do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: 'FakeBlock', required: true %>
        <span class="help-block">The title of the account that will be shown in the chat room heading.</span>
      </div>
    
      <div class="form-group">
        <%= f.label :subdomain %>
        <%= f.text_field :subdomain, class: 'form-control', placeholder: 'fakeblock', required: true %>
        <span class="help-block">Pick a subdomain for your account. You will be able to access your account from <b>your-subdomain.userpub.com</b>.</span>
      </div>
    
      <div class="form-group">
        <%= f.label :support_email %>
        <%= f.text_field :support_email, class: 'form-control', placeholder: 'help@fakeblock.com' %>
        <span class="help-block">The address users should email if no one is around to chat.</span>
      </div>
    
      <div class="form-group">
        <%= f.label :login_url, "Login URL" %>
        <%= f.text_field :login_url, class: 'form-control', placeholder: 'https://auth.fakeblock.com/sso/userpub' %>
        <span class="help-block">The URL that will trigger <%= link_to "JWT-based Single Sign-On", "https://github.com/userpub/userpub/wiki/Single-Sign-On", target: "_blank" %> for your Userpub.</span>
      </div>
    
      <div class="form-group">
        <%= f.label :host, "Custom Domain" %>
        <%= f.text_field :host, class: 'form-control', placeholder: 'pub.fakeblock.com' %>
        <span class="help-block">Specify a custom domain that you will CNAME to <b>your-subdomain-userpub.com</b>. (Optional)</span>
      </div>
    
      <div class="form-group">
        <%= f.label :staff_domain %>
        <%= f.text_field :staff_domain, class: 'form-control', placeholder: 'fakeblock.com' %>
        <span class="help-block">Enter an email domain that will automatically be granted staff acesss. (Optional)</span>
      </div>
    
      <button type="submit" class="btn btn-primary btn-block"><%= account.new_record? ? "Create" : "Update" %> Account</button>
    <% end %>
  </div>
</div>

app/views/accounts/edit.html.erb
<div class="container"><div class="row"><div class="col-md-8 col-md-offset-2">
<%= render "accounts/form", account: @account %>
  </div></div></div>

app/views/accounts/index.html.erb
<% if @accounts.any? %>
<div class='container'>
  <h1>Your Userpubs</h1>
  <table class="table table-bordered">
    <thead><tr><th>Name</th><th>Subdomain</th><th>Custom Domain</th><th>JWT Secret (Hover to Reveal)</th><th>Actions</th></thead>
    <tbody>
      <% @accounts.each do |account| %>
      <tr><th><%= account.name %></th><td><%= link_to account.subdomain, "http://#{account.subdomain}.#{ENV['APP_HOST']}" %></td><td><%= link_to account.host, "http://#{account.host}/" if account.host %></td><td class="secret"><%= account.secret %></td><td><%= link_to "Edit", edit_account_path(account), class: "btn btn-primary btn-xs" %> <%= link_to "Test Login", token_account_path(account), class: 'btn btn-default btn-xs' %></td></tr>
      <% end %>
    </tbody>
  </table>
</div>
<hr>
<% end %>

<div class="container"><div class="row">
  <div class="col-md-4">
    <h2>New Accounts</h2>
    <p>Userpub is a little different from most apps. We aren't going to make your
      users create yet another password just to be able to chat. Instead Userpub
      uses <%= link_to "Single Sign-On", "https://github.com/userpub/userpub/wiki/Single-Sign-On", target: "_blank" %>
      to seamlessly integrate with your application.</p>
    
    <p>We provide you with your own subdomain on userpub.com that you can use for as
      long as you'd like, but if you want to use your own domain name just enter
      one on the right and create a <code>CNAME</code> record pointing to your
      Userpub subdomain.</p>
  </div>
  <div class="col-md-8"><%= render "accounts/form", account: Account.new %></div>
</div></div>

app/views/accounts/new.html.erb
<div class="container"><div class="row"><div class="col-md-8 col-md-offset-2">
<%= render "accounts/form", account: @account %>
  </div></div></div>

app/views/accounts/show.html.erb
<header>
  <nav class="navbar navbar-default account-header navbar-fixed-top"><div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" ng-bind="account.name" href="/">Userpub Account</a>
    </div>
    <div class="btn-group navbar-right navbar-btn account-menu" ng-show="user">
      <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#" ><span class="name" ng-bind="user.d.name">Account Menu</span> <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li>
          <a href="/logout" target="_self">Sign Out</a>
        </li>
      </ul>
    </div>
    <a class="btn btn-default navbar-btn navbar-right account-menu" href="/auth/jwt" target="_self" ng-hide="user">Sign In</a>
    </div></nav>
</header>

<section class="chat container" ng-controller="ChatCtrl">
  <div class="row">
    <div class="col-md-8 col-lg-9">
      <div class="chat-message-window" scroll-on-add="messages">
        <ul class="chat-messages" hide-repeating-names>
          <li ng-repeat="message in messages" class="chat-message" ng-class="{staff: message.user.staff}">
            <span class="author username" ng-bind="message.user.name"> Author Name</span>
            <span class="message" ng-bind-html="message.text | autolink:_blank | emoji | chatMessage">Content of the message goes here.</span>
          </li>
        </ul>
      </div>
      <div class="chat-box-container">
        <form ng-submit="sendMessage()" class="chat-box container" ng-show="user">
          <textarea class="form-control" rows="2" ng-model="draft.text" ng-keypress="messageKeypress($event)"></textarea><button type="submit" class="btn btn-primary">Send</button>
        </form>
        <div class="chat-box" ng-hide="user">
          <p class='lead text-center chat-join'>Join the conversation! <a href="/auth/jwt" target="_self">Sign in Now</a>.</p>
        </div>
      </div>
    </div>
    <aside class="col-md-4 col-lg-3 sidebar"><div class="sidebar-content" sticky="80">
      <div class="panel panel-default sidebar-presence" ng-controller="PresenceCtrl">
        <div class="panel-heading">Online Now</div>
        <div class="panel-body">
          <ul class="online-list">
            <li ng-repeat="connection in connections | orderBy:-staff:name" ng-class="{staff: connection.staff}">
              <span ng-bind="connection.name" class="username">Username</span>
            </li>
        </div>
      </div>
    </div>
    <p><a class="btn btn-block" grant-notification>Enable Browser Notifications</a></p>  
    </aside>
  </div>
</section>

<section class='content' ng-view></section>

app/views/accounts/token.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-6 col-md-offset-3'>
      <div class="alert alert-info">If you want to generate your own tokens, <%= link_to "see the wiki", "https://github.com/userpub/userpub/wiki/Single-Sign-On", target: '_blank', class: 'alert-link' %>.</div>
      <% if @payload %><div class="panel panel-default">
      <div class="panel-heading">Generated Token</div><div class="panel-body">
      <pre><%= @payload %></pre>
      <h3>Login URL</h3>
      <pre><%= link_to "http://#{@account.preferred_host}/auth/jwt/callback?jwt=#{@payload}", "http://#{@account.preferred_host}/auth/jwt/callback?jwt=#{@payload}", target: "_blank" %></pre>
      </div></div>
      <% end %>
      
      <h2>Generate an SSO Token</h2>
      <p class='lead'>Here you can generate a JWT Token to authenticate to your account for testing or manual entry purposes.</p>
      
      <%= form_for :token do |f| %>
        <div class="form-group">
          <%= f.label :id, "ID" %>
          <%= f.text_field :id, class: 'form-control', placeholder: '123', required: true %>
          <span class="help-block">The id of the user.</span>
        </div>  
      
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control', placeholder: 'Bob User', required: true %>
          <span class="help-block">The display name for the user.</span>
        </div>
      
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control', placeholder: 'bob@example.com', required: true %>
          <span class="help-block">The email for the user.</span>
        </div>
      
        <div class="checkbox">
          <%= f.check_box :staff %>
          <%= f.label :staff, "Staff (User's posts will be highlighted as a staff member)" %>
        </div>
      
        <button class="btn btn-block btn-primary" type="submit">Generate Token</button>
      <% end %>
    </div>
  </div>
</div>

app/views/lander/demo.erb
<header class='lander-top'>
  <h1><a href="/">Userpub.</a></h1>
  <h2>Want to take Userpub for a spin? It couldn't be easier.</h2>
</header>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 demo-sign-in">
      <div class="panel panel-primary">
        <div class="panel-heading">Sign into the Demo Account
        </div>
        <div class="panel-body">
          <%= form_tag "/demo", method: "post" do %>
            <div class="form-group">
              <label class="control-label">Your Name</label>
              <div class="controls">
                <input type="text" class="form-control" placeholder="Maurice Moss" name="name">
              </div>
            </div>
            <button type="submit" class="btn btn-warning btn-block">Give it a Spin!</button>
          <% end %>
        </div>
      </div>
      
      <p class="text-center"><i class="icon icon-hand-up"></i></p>
      <p class="lead">Judging is hard, so I tried to make it easy. Just enter your name and you'll be up and running.</p>
      <p>Of course, it would be remiss not to point out that the demo was <b>super easy</b> to create because of Userpub's simple JSON Web Token single sign-on functionality. It takes less than 10 lines of code to integrate your app with Userpub, so really there's no excuse not to do it!</p>
      
      <hr>    
      <p class="text-center">Want to make your own account?</p>
      <a class="btn btn-primary btn-lg btn-block" href="/auth/persona">Get Started Here</a>
   
    </div>
  </div>
</div>

app/views/lander/demo.html.erb
<header class='lander-top'>
  <h1><a href="/">Userpub.</a></h1>
  <h2>Want to take Userpub for a spin? It couldn't be easier.</h2>
</header>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 demo-sign-in">
      <div class="panel panel-primary">
        <div class="panel-heading">Sign into the Demo Account
        </div>
        <div class="panel-body">
          <%= form_tag "/demo", method: "post" do %>
            <div class="form-group">
              <label class="control-label">Your Name</label>
              <div class="controls">
                <input type="text" class="form-control" placeholder="Maurice Moss" name="name" required>
              </div>
            </div>
            <button type="submit" class="btn btn-warning btn-block">Give it a Spin!</button>
          <% end %>
        </div>
      </div>
      
      <p class="text-center"><i class="icon icon-hand-up"></i></p>
      <p class="lead">Judging is hard, so I tried to make it easy. Just enter your name and you'll be up and running.</p>
      <p>Of course, it would be remiss not to point out that the demo was <b>super easy</b> to create because of Userpub's simple <%= link_to "JSON Web Token single sign-on", "https://github.com/userpub/userpub/wiki/Single-Sign-On", target: "_blank" %> functionality. It takes less than 10 lines of code to integrate your app with Userpub, so really there's no excuse not to do it!</p>
      
      <hr>    
      <p class="text-center">Want to make your own account?</p>
      <%= form_tag "/auth/persona/callback", "ng-controller" => "PersonaCtrl", "method" => "post" do %>
        <input name="assertion" type="hidden">
        <button class="btn btn-primary btn-lg btn-block" ng-click="login()" type="button">Get Started Here</button>
      <% end %>
    </div>
  </div>
</div>

app/views/lander/home.erb
<header class='lander-top'>
  <h1>Userpub.</h1>
  <h2>Don't run a help desk, build a community.</h2>
  <p>Userpub is hosted group support chat for startups. It's that simple.</p>
  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1"><a href="/demo"><img src="/images/screenshot.png" alt="Userpub Screenshot" class="img-responsive home-screenshot"></a></div>
  </div>
</header>

<div class="rumble-participant">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-4"><img src="/images/rumble-logo.png" alt="Rails Rumble 2013 Participant" class="img-responsive"></div>
      <div class="col-sm-6 col-md-8 app-info">
        <p class="lead text-center">This app was created for the 2013 Rails Rumble.</p>
        <p class="text-center">
          <a class="btn btn-primary btn-lg" href="/demo">Judging? Launch the Demo</a>
          <a class="btn btn-warning btn-lg" href="http://railsrumble.com/entries/241-userpub" target="_blank">Vote for Userpub!</a>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/lander/home.html.erb
<header class='lander-top'>
  <h1>Userpub.</h1>
  <h2>Don't run a help desk, build a community.</h2>
  <p>Userpub is hosted group support chat for startups. It's that simple.</p>
</header>

<div class="row">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1 text-center"><a href="/demo" track-event="Clicked Demo Link" track-data='{"location":"home_screenshot"}'><img src="/images/screenshot.png" alt="Userpub Screenshot" class="img-responsive home-screenshot"></a></div>
</div>

<div class="text-center lead">
  <a href="/demo" class="btn btn-primary btn-lg" track-event="Clicked Demo Link" track-data='{"location":"home"}'>Check out the Demo</a> or 
  <%= form_tag "/auth/persona/callback", "ng-controller" => "PersonaCtrl", "method" => "post", "style" => "display: inline-block;" do %>
    <input name="assertion" type="hidden">
    <button class="btn btn-warning btn-lg btn" ng-click="login()" type="button">Get Started Here</button>
  <% end %>
</div>

<div class="container">
  <div class="row features">
    <div class="col-md-4 feature">
      <h3><i class="icon icon-comments-alt"></i> Classy Chat</h3>
      <p>Userpub has the niceties you want from a modern chat client. Autolinking,
        emoji, browser notifications, and inline images come standard. We also highlight your team's
        messages for the "official" touch.</p>
    </div>
    <div class="col-md-4 feature">
      <h3><i class="icon icon-key"></i> Bring Your Users</h3>
      <p>Userpub's simple Single Sign-On means your users don't have to sign up for
      yet another account. You can integrate with Userpub in less than 10 lines of
      code.</p>
    </div>
    <div class="col-md-4 feature">
      <h3><i class="icon icon-github"></i> Open Source SaaS</h3>
      <p>Userpub is completely open source released under the MIT License. That means improvements
      from the community, no lock-in, and nothing but good feelings!</p>
    </div>
  </div>
</div>

app/views/layouts/_analytics.html.erb
<script type="text/javascript">
  var analytics=analytics||[];(function(){var e=["identify","track","trackLink","trackForm","trackClick","trackSubmit","page","pageview","ab","alias","ready","group"],t=function(e){return function(){analytics.push([e].concat(Array.prototype.slice.call(arguments,0)))}};for(var n=0;n<e.length;n++)analytics[e[n]]=t(e[n])})(),analytics.load=function(e){var t=document.createElement("script");t.type="text/javascript",t.async=!0,t.src=("https:"===document.location.protocol?"https://":"http://")+"d2dq2ahtl5zl1z.cloudfront.net/analytics.js/v1/"+e+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n)};
  analytics.load("<%= ENV['SEGMENTIO_KEY'] || 'im3h2644lv' %>");
</script>

app/views/layouts/_flashes.html.erb
<div class="container"><% {alert: :danger, notice: :success}.each_pair do |f,a| %>
  <% if flash[f] %><div class="alert alert-<%= a %>"><%= flash[f] %></div><% end %>
  <% end %></div>

app/views/layouts/_footer.html.erb
<hr>
<p class="text-muted text-center">Copyright &copy; <%= Date.today.year %> Michael Bleigh. Built with <%= link_to "Divshot", "http://www.divshot.com/", target: "_blank" %>. <%= link_to "Open Source on GitHub", "https://github.com/userpub/userpub" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="userpub">
<head>
  <title><%= current_account.name %> Community Chat - Powered by Userpub</title>  
  <%= stylesheet_link_tag "application", media: "all" %>
  <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900,200italic,300italic,400italic,600italic,700italic,900italic|Source+Code+Pro|Bree+Serif" rel="stylesheet" type="text/css">
  <link rel="shortcut icon" href="/favicon.ico" />
  <script src="https://cdn.firebase.com/v0/firebase.js"></script>
  <%= render "layouts/analytics" %>
  <script type="text/javascript">
    window.state = {
      user: <%=raw current_user.to_json %>,
      account: <%=raw current_account.to_json %>,
      firebase: "https://<%= ENV['FIREBASE'] %>.firebaseio.com/accounts/<%= current_account.id %>",
      firebase_token: <%=raw current_user.try(:firebase_token).to_json %>
    }
  </script>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body ng-controller="MainCtrl" distance-from-bottom="bottomProximity">
  <%= yield %>
</body>
</html>

app/views/layouts/lander.html.erb
<!DOCTYPE html>
<html ng-app='userpub.lander'>
<head>
  <title>Userpub - Hosted Group Chat Support for Startups</title>  
  <%= stylesheet_link_tag    "lander", media: "all" %>
  <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900,200italic,300italic,400italic,600italic,700italic,900italic|Source+Code+Pro|Bree+Serif" rel="stylesheet" type="text/css">
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="//cdnjs.cloudflare.com/ajax/libs/animate.css/2.0/animate.min.css" rel="stylesheet" type="text/css">
  <script src="https://login.persona.org/include.js" type="text/javascript"></script>
  <%= render "layouts/analytics" %>
  <%= javascript_include_tag "lander" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
  <%= render "layouts/footer" %>
  <script src="http://s0.railsrumble.com/banner.js" type="text/javascript"></script>
</body>
</html>

app/views/layouts/manage.html.erb
<!DOCTYPE html>
<html ng-app='userpub.lander'>
<head>
  <title>Userpub - Manage Accounts</title>  
  <%= stylesheet_link_tag    "lander", media: "all" %>
  <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900,200italic,300italic,400italic,600italic,700italic,900italic|Source+Code+Pro|Bree+Serif" rel="stylesheet" type="text/css">
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <%= render "layouts/analytics" %>
  <script src="https://login.persona.org/include.js" type="text/javascript"></script>
  <%= javascript_include_tag "lander" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="manage-header clearfix">
    <div class="container">
      <h1>Userpub.</h1>
      <p class="pull-right"><%= persona %> <a href="/logout" class="btn btn-default btn-sm">Sign Out</a></p>
    </div>
  </header>
  <%= render "layouts/flashes" %>
  <%= yield %>
  <% if @account %><hr><p class='text-center'>Back to <%= link_to 'Accounts List', accounts_path %></p><% end %>
  <%= render "layouts/footer" %>
</body>
</html>